apiVersion: v1
kind: Service
metadata:
  name: k8s-crash-course-service
spec:
  type: NodePort
  selector:
    app: k8s-crash-course
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
